import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const serati = localFont({
  src: '../public/fonts/Serati-Regular.woff2',
  variable: '--font-primary',
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Отсталая пешка",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${serati.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
